prompt_string=input("Enter A Sting: ")
print(prompt_string[2])
print(prompt_string[-2])
print(prompt_string[:5])
print(prompt_string[:-2])
print(prompt_string[::2])
print(prompt_string[1::2])
print(prompt_string[::-1])
print(prompt_string[-1::-2])
print(len(prompt_string))